document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head lang=\'en\'>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width,initial-scale=1\'/>");
document.writeln("    <title></title>");
document.writeln("    <!--引入文件，必须注意导入顺序-->");
document.writeln("    <link rel=\'stylesheet\' href=\'css/bootstrap.css\'/>");
document.writeln("    <script src=\'js/jquery.min.js\'></script>");
document.writeln("    <script src=\'js/popper.min.js\'></script>");
document.writeln("    <script src=\'js/bootstrap.min.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<style>");
document.writeln("");
document.writeln("");
document.writeln("    .k1{");
document.writeln("        width:248px;");
document.writeln("        height:278px;");
document.writeln("    }");
document.writeln("    .k3 {");
document.writeln("        margin-top:158px;");
document.writeln("    }");
document.writeln("    .k4{");
document.writeln("        width:280px;");
document.writeln("        height:240px;");
document.writeln("        float: left;");
document.writeln("        margin-left: 100px;");
document.writeln("");
document.writeln("    }");
document.writeln("     p,h6{");
document.writeln("        color:#6c757d;");
document.writeln("    }");
document.writeln("");
document.writeln("</style>");
document.writeln("<div class=\'container\'>");
document.writeln("");
document.writeln("");
document.writeln("    <hr/>");
document.writeln("   <div class=\'foot-jb mt-5 mr-4\'>");
document.writeln("       <div class=\'k1 ml-2 float-left\'>");
document.writeln("          <h6 class=\'font-weight-bold p-2\'>关于Starry Sky Collect</h6>");
document.writeln("           <p class=\'p-2\'>SSC是一家报刊阅读杂志，我们的全球足迹和基于云的平台为客户提供了阅读的最简单方法。我们通过提供易用性，速度，质量和价值来衡量我们取悦客户的能力。SSC已经履行了这项使命。</p>");
document.writeln("       </div>");
document.writeln("       <div class=\'k4 \'>");
document.writeln("           <img src=\'images/weibo-logo.jpg\' class=\'float-left mr-4\' width=\'80px\' height=\'80px\' alt=\'\'/>");
document.writeln("           <div class=\'float-left\'>");
document.writeln("           <h6 class=\'font-weight-bold p-2\'>SSC官方微博</h6>");
document.writeln("           <p>扫一扫立即关注官方微博</p>");
document.writeln("           <img src=\'images/weibo-share.png\' alt=\'\'/>");
document.writeln("           </div>");
document.writeln("       </div>");
document.writeln("       <div class=\'k2 float-right \'>");
document.writeln("          <h6 class=\'font-weight-bold text-center p-2\'>与此同时，在别处</h6>");
document.writeln("           <a href=\'\'>");
document.writeln("               <img class=\'mr-3\' src=\'img/icon_home1.png\' alt=\'\'/>");
document.writeln("           </a>");
document.writeln("           <a href=\'\'>");
document.writeln("               <img class=\'mr-3\' src=\'img/icon_home2.png\' alt=\'\'/>");
document.writeln("           </a>");
document.writeln("           <a href=\'\'>");
document.writeln("               <img class=\'mr-3\' src=\'img/icon_home3.png\' alt=\'\'/>");
document.writeln("           </a>");
document.writeln("           <a href=\'\'>");
document.writeln("               <img class=\'mr-3\' src=\'img/icon_home4.png\' alt=\'\'/>");
document.writeln("           </a>");
document.writeln("       </div>");
document.writeln("       <div class=\'k3 float-left mt-0\'>");
document.writeln("       <p class=\'text-center small p-2 m-0\'>版权所有© CORVUS DESIGN STUDIO。版权所有。</p>");
document.writeln("       <p class=\'text-center small p-2 m-0\'>该网站及其中的所有内容均由CORVUS DESIGN STUDIO内部设计和开发。");
document.writeln("           不允许未经授权的重复内容或设计。</p>");
document.writeln("       </div>");
document.writeln("   </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");