document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head lang=\'en\'>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width,initial-scale=1\'/>");
document.writeln("    <title></title>");
document.writeln("    <!--引入文件，必须注意导入顺序-->");
document.writeln("    <link rel=\'stylesheet\' href=\'css/bootstrap.css\'/>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/header.css\'/>");
document.writeln("    <script src=\'js/jquery.min.js\'></script>");
document.writeln("    <script src=\'js/popper.min.js\'></script>");
document.writeln("    <script src=\'js/bootstrap.min.js\'></script>");
document.writeln("    <style>");
document.writeln("");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'container\'>");
document.writeln("    <!--<div class=\'head-bg position-relative\'>-->");
document.writeln("        <!--<img src=\'\'  alt=\'\'/>-->");
document.writeln("    <!--</div>-->");
document.writeln("    <div class=\'top-1 m-0 \'>");
document.writeln("        <div class=\'nav m-0\'>");
document.writeln("            <ul class=\'breadcrumb   m-0\'>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a class=\'font-weight-bold \' href=\'#\'>SSC移动</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a class=\'font-weight-bold\' href=\'#\'><span>SSCVip</span></a>");
document.writeln("                </li>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a class=\'font-weight-bold\' href=\'#\'>订阅</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a class=\'font-weight-bold\' href=\'#\'>SSC专栏</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a class=\'font-weight-bold\' href=\'#\'>更多</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("       <div class=\'search position-absolute\'>");
document.writeln("          <input  type=\'search\' class=\'form-control float-left ml-2\' placeholder=\'search your want\'/>");
document.writeln("          <div class=\'input-group-append\'>");
document.writeln("              <img class=\'btn p-0\' src=\'images/search.jpg\' alt=\'\' width=\'38px\' height=\'37px\'/>");
document.writeln("          </div>");
document.writeln("           <div class=\'register position-absolute\'>");
document.writeln("             <button data-toggle=\'modal\' data-target=\'#mymodal1\' class=\'btn btn-default p-1 m-0 font-weight-bold reg\' href=\'\'>注册</button>");
document.writeln("               <div class=\'modal\' id=\'mymodal1\'>");
document.writeln("                   <div class=\'modal-dialog\'>");
document.writeln("                       <div class=\'modal-content\'>");
document.writeln("                           <div class=\'modal-header p-0\'>");
document.writeln("                               <div class=\'gb\'>");
document.writeln("                                   <button class=\'close mt-2\' data-dismiss=\'modal\'>&times;</button>");
document.writeln("                                   <!--<img src=\'img/xk.jpg\' width=\'100%\' alt=\'\'/>-->");
document.writeln("                               </div>");
document.writeln("                               <div class=\'m-auto p-2\'><h3>用户注册</h3></div>");
document.writeln("                           </div>");
document.writeln("                           <div class=\'modal-body\'>");
document.writeln("                               <form action=\'\'>");
document.writeln("                                   <div class=\' text-center\'>用户姓名：<input type=\'text\'/></div>");
document.writeln("                                   <div class=\'mt-2 text-center\'>用户密码：<input type=\'text\'/></div>");
document.writeln("                                   <div class=\'mt-2 text-center\'>邮箱注册：<input  type=\'text\'/></div>");
document.writeln("                                   <div class=\'text-center mt-2\'>个性签名：<input type=\'text\'/></div>");
document.writeln("                               </form>");
document.writeln("                           </div>");
document.writeln("                           <div class=\'modal-footer\'>");
document.writeln("                               <button class=\'btn-lg btn-block p-0 m-auto btn text-center btn-danger\' data-dismiss=\'modal\' >注册我</button>");
document.writeln("");
document.writeln("                           </div>");
document.writeln("                           <div class=\'small p-3\'>注册即表示您同意接收Starry Sky Collect的电子邮件更新。您可以随时取消订阅，并可在此处查看我们的 <a href=\'#\'>隐私政策</a>。</div>");
document.writeln("                       </div>");
document.writeln("                   </div>");
document.writeln("               </div>");
document.writeln("             <b class=\'p-1 m-0 font-weight-bold\' >|</b>");
document.writeln("             <button data-toggle=\'modal\' data-target=\'#mymodal2\'  class=\'btn btn-default p-1 m-0 font-weight-bold login\' href=\'\'>登录</button>");
document.writeln("               <div class=\'modal\' id=\'mymodal2\'>");
document.writeln("                   <div class=\'modal-dialog\'>");
document.writeln("                       <div class=\'modal-content\'>");
document.writeln("                           <div class=\'modal-header p-0\'>");
document.writeln("                               <div class=\'gb\'>");
document.writeln("                                   <button class=\'close mt-2\' data-dismiss=\'modal\'>&times;</button>");
document.writeln("                                   <!--<img src=\'img/xk.jpg\' width=\'100%\' alt=\'\'/>-->");
document.writeln("                               </div>");
document.writeln("                               <div class=\'m-auto p-2\'><h3>账号登录</h3></div>");
document.writeln("                           </div>");
document.writeln("                           <div class=\'modal-body p-5\'>");
document.writeln("                               <form class=\'mt-2\' action=\'\'>");
document.writeln("                                   <div class=\' text-center mr-3\'>用户名：<input type=\'text\'/></div>");
document.writeln("                                   <div class=\'mt-4 text-center\'>密码：<input  type=\'text\'/></div>");
document.writeln("");
document.writeln("                               </form>");
document.writeln("                           </div>");
document.writeln("                           <div class=\'modal-footer m-auto\'>");
document.writeln("                               <button class=\'btn-lg btn-block p-0 btn btn-danger\' data-dismiss=\'modal\'>登录</button>");
document.writeln("");
document.writeln("                           </div>");
document.writeln("                           <div class=\'small p-3 text-center\'>#欢迎访问此网站，登录后进入Starry Sky Collect杂志。 </div>");
document.writeln("                       </div>");
document.writeln("                   </div>");
document.writeln("               </div>");
document.writeln("           </div>");
document.writeln("       </div>");
document.writeln("        <div class=\'kong\'></div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'top-2\'>");
document.writeln("        <div class=\'nav mt-2 float-left\'>");
document.writeln("            <ul class=\'breadcrumb m-0\'>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a  target=\'_blank\' href=\'index1.html\'>首页</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a  target=\'_blank\' href=\'index2.html\'>潮流</a>");
document.writeln("                    <ul>");
document.writeln("                        <li>风格示范</li>");
document.writeln("                        <li>时尚街拍</li>");
document.writeln("                        <li>降价商品</li>");
document.writeln("                        <li><hr></li>");
document.writeln("                        <li>发现社区</li>");
document.writeln("                        <li>新秀场</li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a class=\'\' href=\'#\'>热门</a>");
document.writeln("                    <ul>");
document.writeln("                        <li>时装</li>");
document.writeln("                        <li>秀场</li>");
document.writeln("                        <li>鞋包</li>");
document.writeln("                        <li><hr></li>");
document.writeln("                        <li>美容</li>");
document.writeln("                        <li>珠宝</li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a class=\'\' target=\'_blank\' href=\'index5.html\'>人物</a>");
document.writeln("                    <ul>");
document.writeln("                        <li>星话题</li>");
document.writeln("                        <li>明星街拍</li>");
document.writeln("                        <li>派对盛事</li>");
document.writeln("                        <li><hr></li>");
document.writeln("                        <li>圈内名流</li>");
document.writeln("                        <li>SSC对话</li>");
document.writeln("                        <li>精彩专题</li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\'breadcrumb-item\'>");
document.writeln("                    <a class=\'\' href=\'index4.html\' target=\'_blank\'>生活</a>");
document.writeln("                    <ul>");
document.writeln("                        <li>旅行</li>");
document.writeln("                        <li>家居</li>");
document.writeln("                        <li>美食</li>");
document.writeln("                        <li><hr></li>");
document.writeln("                        <li>职场</li>");
document.writeln("                        <li>文化艺术</li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-part1 float-left  ml-2 mt-2\'>");
document.writeln("            <a href=\'#\' class=\'p-1\'>发现</a>");
document.writeln("");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-part2 float-left p-2 ml-2\'>");
document.writeln("            <a  target=\'_blank\' href=\'index3.html\'>杂志</a>");
document.writeln("            <a href=\'index6.html\' target=\'_blank\' class=\'word p-2\'>SSCFilm</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-part3 float-left ml-2\'>");
document.writeln("            <a href=\'\'>论坛</a>");
document.writeln("            <a href=\'\'>博客</a>");
document.writeln("            <a href=\'\'>活动</a>");
document.writeln("            <a href=\'\'>品牌</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'n1\'></div>");
document.writeln("    </div>");
document.writeln("    <hr height=\'5px\' class=\'mb-3\' color=\'#eee\' width=\'100%\'/>");
document.writeln("    <div class=\'title\'>");
document.writeln("        <div>");
document.writeln("            <img src=\'images/web-title.png\' alt=\'\'/>");
document.writeln("            <img class=\'ml-2 mt-1\' src=\'images/title.com.png\' alt=\'\'/>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");